[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bonding_curve_system = "AfWjSFSNxYJeXxPTfJvRynbYXnmFrMRaN2UXgr2LTrt7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "echo 'Tests should be run from the frontend directory with npm test'"
