[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bonding_curve_system = "J72SyAhR7pwGfMvzSNrDTpkfmWSpNp2oqiR5hY5mWBf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
