version: '3'
services:
  solana-dev:
    image: random-sol_contracts-solana-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - solana-config:/root/.config/solana
      - cargo-registry:/root/.cargo/registry
    ports:
      - "8080:8080"
    environment:
      - ANCHOR_WALLET=/root/.config/solana/id.json
    command: tail -f /dev/null

volumes:
  solana-config:
  cargo-registry:
